gist/urls.py
from django.conf.urls import patterns, include, url

from views import *

urlpatterns = patterns('',
    url(r'^$', list_view),
    url(r'^gist-(?P<gist_pk>\d+)/$', gist_view),
    url(r'^tag-(?P<tag_pk>\d+)/$', list_view),
)

project/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include("gist.urls")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gist/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User)

    name = models.CharField(max_length=64)
    bio = models.TextField(blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    avatar = models.ImageField(upload_to="gist/user/avatar", blank=True, null=True)

    def __unicode__(self):
        return self.user.username

class Tag(models.Model):
    name = models.CharField(max_length=32)

    def __unicode__(self):
        return self.name    

class Gist(models.Model):
    author = models.ForeignKey(User)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True, null=True)

    def __unicode__(self):
        return self.name

class File(models.Model):
    gist = models.ForeignKey(Gist)
    name = models.CharField(max_length=255)
    file_name = models.CharField(max_length=64, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    content = models.TextField()

    def __unicode__(self):
        return "%s %s" % (self.gist, self.name)

gist/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse

from models import Gist, Tag

def list_view(request, tag_pk=None, template="gist/home.html"):
    qs = Gist.objects.order_by("-pk")
    if tag_pk:
        qs = qs.filter(tags=tag_pk)
    return render_to_response(template,
        {
            "gist_qs": qs,
            "tag_qs": Tag.objects.order_by("name"),
        },
        context_instance=RequestContext(request))

def gist_view(request, gist_pk, template="gist/gist.html"):
    return render_to_response(template,
        {
            "gist": get_object_or_404(Gist, pk=gist_pk),
            "tag_qs": Tag.objects.order_by("name"),
        },
        context_instance=RequestContext(request))

gist/templates/gist/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Gist</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="{{STATIC_URL}}gist/bootstrap/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
      }
      h3 {
        margin: 0px;
        line-height: 1;
      }
    </style>
    <link href="{{STATIC_URL}}gist/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{{STATIC_URL}}gist/bootstrap/js/html5shiv.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="span3">
            {% if user.userprofile.avatar %}
                <img src="{{user.userprofile.avatar.url}}">
            {% else %}
                <img src="http://placehold.it/300x300">
            {% endif %}
            <h2>{{user.userprofile.name}}</h2>
            <p>{{user.userprofile.bio|linebreaksbr}}</p>
            <p>{{user.userprofile.location}}</p>
            <p><a href="{{user.userprofile.url}}" target="blank">{{user.userprofile.url}}</a></p>
        </div>
        <div class="span7">
          {% block content %}
          {% endblock content %}
        </div>
        <div class="span2">
            <p><a href="/">home</a></p>
            <p style="line-height:2.2;">{% for tag in tag_qs %}<a href="/tag-{{tag.pk}}" class="btn btn-small">{{tag.name}}</a> {% endfor %}</p>
        </div>
      </div>
      <hr>
      2013 <a href="http://ondrejsika.com">Ondrej Sika</a>
    </div>


    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{STATIC_URL}}gist/bootstrap/js/jquery.js"></script>
    <script src="{{STATIC_URL}}gist/bootstrap/js/bootstrap-transition.js"></script>
    <script src="{{STATIC_URL}}gist/bootstrap/js/bootstrap-alert.js"></script>
    <script src="{{STATIC_URL}}gist/bootstrap/js/bootstrap-modal.js"></script>
    <script src="{{STATIC_URL}}gist/bootstrap/js/bootstrap-dropdown.js"></script>
    <script src="{{STATIC_URL}}gist/bootstrap/js/bootstrap-scrollspy.js"></script>
    <script src="{{STATIC_URL}}gist/bootstrap/js/bootstrap-tab.js"></script>
    <script src="{{STATIC_URL}}gist/bootstrap/js/bootstrap-tooltip.js"></script>
    <script src="{{STATIC_URL}}gist/bootstrap/js/bootstrap-popover.js"></script>
    <script src="{{STATIC_URL}}gist/bootstrap/js/bootstrap-button.js"></script>
    <script src="{{STATIC_URL}}gist/bootstrap/js/bootstrap-collapse.js"></script>
    <script src="{{STATIC_URL}}gist/bootstrap/js/bootstrap-carousel.js"></script>
    <script src="{{STATIC_URL}}gist/bootstrap/js/bootstrap-typeahead.js"></script>
</body>
</html>

gist/templates/gist/gist.html
{% extends "gist/base.html" %}
{% block content %}
    <p><a href="/"><< home</a></p>
    <h2>{{gist.name}}</h2>
    <p>{% for tag in gist.tags.all %}<a href="/tag-{{tag.pk}}" class="btn btn-small">{{tag.name}}</a> {% endfor %}</p>
    <p>{{gist.description|linebreaksbr}}</p>
    {% if gist.content %}<pre>{{gist.content}}</pre>{% endif %}

    {% for file in gist.file_set.all %}
    <h4>{{file.name}}</h4>
    <p><code>{{file.file_name}}</code></p>
    <p>{{file.description|linebreaksbr}}</p>
    <pre>{{file.content}}</pre>
    {% endfor %}
{% endblock content %}

gist/templates/gist/home.html
{% extends "gist/base.html" %}
{% block content %}
    {% for gist in gist_qs %}
    <div class="row"><div class="span9">
        <a href="/gist-{{gist.pk}}"><h3>{{gist.name}}</h3></a>
        <p>{% for tag in gist.tags.all %}<a href="/tag-{{tag.pk}}">{{tag.name}}</a> {% endfor %}</p>
        <p>{{gist.description|linebreaksbr}}</p>
        <p>{% for file in gist.file_set.all %}{% if file.file_name %}<code>{{file.file_name}}</code> {% endif %}{% endfor %}</p>
    </div></div>
    <hr style="margin: 0 0 20px 0;">
    {% endfor %}
{% endblock content %}